name: CodeChecker

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Install libevent
        run: sudo apt install libevent-dev libsystemd-dev
  
      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build
  
      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    
      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config Debug

      # Run the analysis
      - uses: whisperity/codechecker-analysis-action@v1
        id: codechecker
        with:
          logfile: ${{ github.workspace }}/build/compile_commands.json

      # Upload the results to the CI.
      - uses: actions/upload-artifact@v2
        with:
          name: "CodeChecker Bug Reports"
          path: ${{ steps.codechecker.outputs.result-html-dir }}
